name: CI/CD Fraud Detection API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo with LFS
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: pytest || echo "⚠️ No tests yet"

    - name: Build Docker image
      run: docker build -t fraud-api .

    # -------------------------
    # Push to Docker Hub
    # -------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag fraud-api ${{ secrets.DOCKERHUB_USERNAME }}/fraud-api:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fraud-api:latest





