name: Fraud Detection CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # 3. Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Train model
    - name: Train Fraud Detection Model
      run: |
        python fraudDetetection.py

    # 5. Test single transaction API
    - name: Start FastAPI Server
      run: |
        nohup uvicorn app:app --host 0.0.0.0 --port 8000 &
      shell: bash

    - name: Wait for server
      run: sleep 10

    - name: Test API
      run: |
        python test_API.py

    # 6. Kill FastAPI server
    - name: Stop FastAPI
      run: |
        pkill -f "uvicorn"
      shell: bash
